name: 'sfdx-orgdev-build-deploy'
author: Tiago Nascimento - tnascimento@salesforce.com
description: 'Convert a Salesforce DX project into a metadata package and deploy it'
inputs:
    type:
        description: 'Type of deployment, could be one of the two: production or sandbox (default)'
        required: true
        default: 'sandbox'

    certificate_path:
        description: 'Path for the encrypted certificate to be used on force:auth:jwt:grant'
        required: true

    decryption_key:
        description: 'Decryption key to be used to decrypt the certificate'
        required: true
    
    decryption_iv:
        description: 'Decryption IV to be used to decrypt the certificate'
        required: true
    
    client_id:  
        description: 'Client ID / Consumer Key of a connected app to the target destination'
        required: true

    username:
        description: 'Username to be used to connect in the target org'
        required: true

    checkonly:
        description: 'Boolean (true/false) that will indicate whether the deploy is a checkonly deploy or not. If is a checkonly, on force:mdapi:deploy command the option -c will be appended'
        required: true
        default: true

    manifest_path:
        description: 'Path on the current repository to one or more package.xml that represents the packages to be deployed. Based on this files the metadata package will be created and deployed in the order specified'
        required: true

    deploy_testlevel:
        description: 'Specifies which tests are run as part of a deployment. Valid values are: NoTestRun, RunSpecifiedTests, RunLocalTests, RunAllTestsInOrg'
        required: true
        default: RunLocalTests

    destructive_path:
        description: 'Path for the destructive changes directory'
        required: false
    
    data_factory:
        description: 'Path on the current repository to the apex script that will be used to create data required by the package'
        required: false

runs:
    using: 'node12'
    main: 'dist/index.js'

branding:
    icon: 'cloud-lightning'
    color: 'blue'
